### ISSUE TITLE
Support pyproject.toml for configuration

### ISSUE THREAD

**Issue by physici** [python-lsp/pylsp-mypy#33]
The standard mypy accepts "pyproject.toml"-files for configuration if no other mypy-configuration files are found. Currently the allowed conf-files for this lsp-plugin are hardcoded into this plugin

[plugin.py, line 334]
    `mypyConfigFile = findConfigFile(workspace, ["mypy.ini", ".mypy.ini"])`

So when running mypy via the lsp, my configurations in the toml-file are ignored. Hence, I would suggest a change of the code to:

[plugin.py, line 334]
    `mypyConfigFile = findConfigFile(workspace, ["mypy.ini", ".mypy.ini", "pyproject.toml"])`

With this change my projects work again.

**Comment by Richardk2n** [comment]
The issue with this is, that it would break mypy configs for everyone not using pyproject.toml.

So I took the liberty to expand on this idea somewhat.

Feel free to look at current master and see if this suits you.

**Comment by physici** [comment]
Your changes work well. Thanks for the update.
