### ISSUE TITLE
No luck getting it to run

### ISSUE THREAD

**Issue by silentjay** [python-lsp/pylsp-mypy#35]
No luck getting this plugin to run, I've installed `pylsp-mypy` globally with `pip install pylsp-mypy`, same as `pylsp` and `mypy`:

```
>which mypy
/home/me/.local/bin/mypy
>which pylsp
/home/me/.local/bin/pylsp
>which python
/usr/bin/python
>python --version
Python 3.9.7
```

My init.vim:

```
local servers = {'pylsp', 'sourcery', 'sumneko_lua', 'html', 'cssls',
                          'jsonls', 'quick_lint_js', 'eslint'}

lspconfig.pylsp.setup {
    on_attach = on_attach, capabilities = capabilities,
    settings = {pylsp = 
                    {
                            configurationSources = {'flake8'},
                            plugins = {
                                 pydocstyle = { enabled = true },
                                 mccabe = { enabled = true },
                                 flake8 = { enabled = true },
                                 pylsp_mypy = { 
                                                 enabled = true,
                                                 live_mode = true,
                                                 dmypy = true, -- speedup
                                             },
                                 pylsp_black = { enabled = true },
                                 pyls_isort = { enabled = false },
                             }
                    }
                }
}
```

Running neovim from inside the project venv or not in a venv makes no difference. I don't know if it's related but from what I can tell neither `pyls_isort` nor `pylsp_black` run either, although the others such as `mccabe` and `flake8` do. (UPDATE - `pylsp_black` does run as expected)

![image](https://user-images.githubusercontent.com/3902481/169251258-79949cd7-761b-4d33-a7da-a6445a4b4019.png)

**Comment by Richardk2n** [comment]
Do `pylsp_black` and `pyls_isort` run, if you remove `pylsp_mypy`?

Meaning:
Is this a problem specific to this plugin?

**Comment by silentjay** [comment]
No they don't run, or at least not what I can tell...e.g. I can run the formatting command with the black plugin installed and the code does get formatted but have no idea if it's black formatting the code or something else. 

At the same time the other plugins such as `flake8`, `mccabe`, `pydocstyle` etc do 100% run fine and I can toggle them on and off. 

How am I meant to debug `pylsp-mypy`? All these `pylsp` plugins seem like black boxes to me.

**Comment by silentjay** [comment]
OK just tried enabling/disabling `pylsp_black` and running the format command, and it's definitely black doing the formatting as no formatting occurs once `pylsp_black` is disabled. So looks like it is an `pylsp-mypy` specific issue I'm having.

**Comment by Richardk2n** [comment]
There are log files, but their location depends on how you run the language server

The language server runs the plugins as subprocesses, by looking at your running processes you can usually find which python process is pylsp-mypy. For there you can bind a console to the output stream of that process and get the log this way.

I assume `-- speedup` is a comment?
Maybe try removing that.
Also live_mode and dmypy cannot work together. If both are set active dmypy is automatically disabled. This should not cause an issue but maby its worth trying if changing this helps.

For further ideas, I need logs.

**Comment by silentjay** [comment]
Thanks for your help, I did try remove the comment and remove the other options such as live_mode previously without any luck.

Your comment about the processes however made me fire up htop and try to hunt down pylsp-mypy, where I discovered pylsp is running in it's own venv which I had no idea about:
![image](https://user-images.githubusercontent.com/3902481/169282366-8e06b972-0910-4384-849e-090e4966f37e.png)

So I simply activated the venv, ran `pip install pylsp-mypy` and now it works as expected!

![image](https://user-images.githubusercontent.com/3902481/169282058-50258d58-6509-4bd4-935b-989b93eb0b54.png)

Not really sure why I have to activate the `pylsp` venv and then install the plugin, there's no mention of having to do this on the `pylsp` docs

**Comment by Richardk2n** [comment]
Well, it is sensible, that pylsp only loads plugins installed in the same environment (in fact it would be terrible if this where not the case).

Venvs can be a little tricky but pylsp and pylsp-mypy handle them well (by now).

The reason why pylsp doc does not mention this is, that usually you are the one managing your venvs and of course you would install the server and the plugin in the same venv, which works.

It is a bit odd, that the installer you used made a seperate venv for pylsp (there are probably good reasons). Thats why they have this:
https://github.com/williamboman/nvim-lsp-installer/tree/main/lua/nvim-lsp-installer/servers/pylsp#readme

Most such installers just install all third party plugins so that no such issues occure (which likely explains why this readme is this well hidden), however due to the fact pylsp-mypy is newer than the others it might not be included everywhere (or has not been when you ran the installer)

**Comment by silentjay** [comment]
@sandangel ensure pylsp-mypy is installed in the correct venv, see my previous comments. If it is installed correctly then open a new issue as my configuration problem was resolved and this issue closed.

**Comment by sandangel** [comment]
@silentjay they are installed in the same venv using `nvim-lsp-install`. could you share your current config with pylsp 1.5.0 and pylsp-mypy 0.6.2?
<img width="2033" alt="image" src="https://user-images.githubusercontent.com/22189661/179488424-3f38b326-c5ae-49a6-931b-486a9f534345.png">

**Comment by sandangel** [comment]
hmm, I think this is more like because I'm using nixos. 🥲
