### ISSUE TITLE
Add support for error end locations

### ISSUE THREAD

**Issue by AntonVucinic** [python-lsp/pylsp-mypy#61]
I just started using this plugin in neovim and noticed that errors weren't underlined properly.
After a quick look at the source code it seems as this is a simple and easy fix:
 - instead of the `--show-column-numbers` option use `--show-error-end` option
 - modify the `line_pattern` regex
 - modify the `parse_line` function with correct diagnostic end location
 - remove the comment on line 100 :)

[link](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-show-error-end) to mypy doc explaining the `--show-error-end` option

If you give me the green light I am willing to make a PR by myself.

**Comment by Richardk2n** [comment]
Sure go ahead.
This requires mypy v0.981 or above, feel free to set that as a dependency.
