### ISSUE TITLE
Diagnostic message cutoff

### ISSUE THREAD

**Issue by tleplaearthur** [python-lsp/pylsp-mypy#66]
My mypy configuration sets `pretty` which I want to keep for when I'm running mypy in my pre-commit hook in the terminal. But when this is set to true, I also can't see the full diagnostic message in neovim. Most of the message is cutoff. Is there way to disable the `pretty` setting only in pylsp?

**Comment by Richardk2n** [comment]
You could use different config files, that are otherwise identical.
